### ISSUE TITLE
Doesn't support text selection within a text layer

### ISSUE THREAD

**Issue by tarngerine** [kylehickinson/Sketch-SF-UI-Font-Fixer#1]
e.g. i have a text layer with mulitple sizes and i want to select a part of a text layer to track

**Comment by kylehickinson** [comment]
It would be cool to fix this, unfortunately I don't think I see anything in the Sketch API that allows me to actually dig deeper into layer selection.  I can get a `MSTextLayer`, but that layer doesn't have any property indicating that the user is currently **editing** said layer or give me a selection range.  And then the `setCharacterSpacing` method applies to the entire layer, not any given range.  [This is all I get to read/write with the text layer](http://bohemiancoding.com/sketch/support/developer/03-reference/MSTextLayer.html).

Would definitely like to fix this up when they expose more accessors in `MSTextLayer` :)

**Comment by tarngerine** [comment]
We've been exploring this in depth at Facebook. We've gone pretty deep by exposing the text layers NSTextStorage but have run into issues with line height (everything else is working).

**Comment by kylehickinson** [comment]
If you can publish a safe/stable workaround for this, that would be awesome! :)

**Comment by kylehickinson** [comment]
This is now working in v2.0.2 beta (https://github.com/kylehickinson/Sketch-SF-UI-Font-Fixer/releases/tag/v2.0.2)
