### ISSUE TITLE
Sketch 48 - Crashing with plugin enabled

### ISSUE THREAD

**Issue by iamsankalp** [kylehickinson/Sketch-SF-UI-Font-Fixer#14]
Hey @kylehickinson! Sketch just released a new updated i.e. 48.

As referenced in #13 - I was using the beta plugin, it's crashing Sketch while opening a file. Please have a look at your convenience.

Thanks a lot,
Sankalp

**Comment by kylehickinson** [comment]
Thanks for letting me know :) I'll check it out

**Comment by kylehickinson** [comment]
Fixed! (2a20641)
