### ISSUE TITLE
Not working for 12 pt text layers

### ISSUE THREAD

**Issue by ghost** [kylehickinson/Sketch-SF-UI-Font-Fixer#4]
OS X 10.11.3 (15D21)
Sketch 3.5.2 (25235)

**Comment by kylehickinson** [comment]
Technically the 12pt font has 0 adjustments to its character spacing.  Is it not changing the character spacing to 0?

**Comment by ghost** [comment]
Nope. It stays the same non-zero value. Not a very serious issue to most since 0 is the default value. But my file had been screwed up by another plugin and I had to change them one by one. All 12 pt text layers stayed unchanged while it worked well on all the others. Checked the code and haven't got a clue why.

**Comment by kylehickinson** [comment]
Weird, I shall check it out!

**Comment by kylehickinson** [comment]
Ummm `setCharacterSpacing` seems to be gone from `MSTextLayer`? http://developer.sketchapp.com/reference/MSTextLayer/

😐 RIP plugin? I'll contact the Sketch team
