### ISSUE TITLE
Having Trouble Using Plugin

### ISSUE THREAD

**Issue by aidantoole** [kylehickinson/Sketch-SF-UI-Font-Fixer#5]
I had a friend who is in the Apple Dev program download the font directly from Apple's site and fwd me the zip file, but the plugin doesn't seem to be working with it. Font sizes are at the appropriate size within my sketch file for the different font types. I've tried uninstalling and reinstalling the plugin and that didn't help either. Any advice?

**Comment by kylehickinson** [comment]
Are you designing at 1x or 2x? :)

I check the plugin every update and haven't had any issues personally but I only design in 1x. The font tracking table was built for 1x only.

**Comment by aidantoole** [comment]
Yeah I'm using the standard iPhone 6 artboards - 375 x 667 px, so yeah I'm designing at 1x

**Comment by kylehickinson** [comment]
I assume you're using the latest version of Sketch?

**Comment by aidantoole** [comment]
up to date, running 39.1

**Comment by aidantoole** [comment]
idk if it matters but the fonts were downloaded as "San Francisco Text", "San Francisco Display" as opposed to "SFUI Text", "SFUI Display"

**Comment by kylehickinson** [comment]
Can you check Font Book and see what they're font-family name is? It should be `SF UI Text` and `SF UI Display` like so:

![screen shot 2016-08-12 at 8 55 25 pm](https://cloud.githubusercontent.com/assets/529104/17640529/47ae1406-60cf-11e6-9a54-e2a11ce12fd9.png)

**Comment by aidantoole** [comment]
They are named San Francisco Text and San Francisco Display. I assume this is the problem?

![screen shot 2016-08-15 at 9 55 27 am](https://cloud.githubusercontent.com/assets/20991996/17666521/805416a6-62ce-11e6-8ca8-63da044cc34d.png)

**Comment by kylehickinson** [comment]
Yeah thats not the correct font.  From that image it looks like you actually have SF Compact Display and SF Compact Text fonts, which are the watch fonts.  Those were originally the only SF fonts we had because it was first released with watchOS.

You'll have to download the official ones from https://developer.apple.com/fonts/ They come in the file "SFUI.zip".

**Comment by aidantoole** [comment]
would it work to rename the fonts?

**Comment by kylehickinson** [comment]
Not unless you edit the actual font data. The postscript names are written to the file itself, the file name really has no effect on it.

**Comment by aidantoole** [comment]
ok, thanks
