### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by jmzyork** [kylehickinson/Sketch-SF-UI-Font-Fixer#7]
Really wish this plug in worked. Exactly what Im looking for. Nothing happens...

**Comment by kylehickinson** [comment]
Just tested on Sketch 41.2, macOS 10.12.2 and everything seems to be working.

- Are your text layers using the correct font? (SF UI Text for < 20pt, SF UI Display for >= 20 pt). Using SF UI Text on a layer which is greater than 20 points won't switch it over. Although maybe its a good idea for me to add a check for that and maybe swap the font through the plugin.
- Are your San Francisco fonts official ([download here](http://developer.apple.com/fonts/)). If they are not, chances are they don't have the proper font postscript name that the plugin is checking for

**Comment by jmzyork** [comment]
Hey Kyle

Yes latest correct sf font downloaded from apple developer site. Im aware of the 20 pt. I also re downloaded the plug in and sketch is updated.

Ill try removing and reinstalling tomorrow

Thanks
James


. .: ::iPhone

**Comment by kylehickinson** [comment]
Also note that when you do activate the plugin, the selected text layer character spacing will change but not update the inspector.  If you de-select and re-select then it will show the updated value.
